import { Calendar, Clock, CheckCircle2, Circle } from "lucide-react";

const scheduleData = [
  {
    date: "Today — Mon 8 Jun",
    items: [
      { topic: "Retrieval Practice — Testing Effect", type: "Flashcard", duration: "8 min", urgency: "overdue", done: false },
      { topic: "Spaced Practice vs Cramming", type: "Quiz (3 Qs)", duration: "6 min", urgency: "overdue", done: false },
      { topic: "Bjork: Learning vs Performance", type: "Elaboration", duration: "10 min", urgency: "due", done: false },
    ],
  },
  {
    date: "Tomorrow — Tue 9 Jun",
    items: [
      { topic: "Bjork's Desirable Difficulties", type: "Flashcard", duration: "5 min", urgency: "upcoming", done: false },
      { topic: "Cognitive Load Theory", type: "Flashcard", duration: "5 min", urgency: "upcoming", done: false },
    ],
  },
  {
    date: "Thu 11 Jun",
    items: [
      { topic: "Interleaving vs Blocking", type: "Quiz (4 Qs)", duration: "8 min", urgency: "upcoming", done: false },
      { topic: "Worked Examples & Expertise Reversal", type: "Elaboration", duration: "12 min", urgency: "upcoming", done: false },
    ],
  },
  {
    date: "Sun 15 Jun",
    items: [
      { topic: "Elaboration / Self-explanation", type: "Flashcard", duration: "5 min", urgency: "upcoming", done: false },
      { topic: "Dual Coding — Mayer's Principles", type: "Quiz (3 Qs)", duration: "6 min", urgency: "upcoming", done: false },
      { topic: "Full Week 1 Brain Dump", type: "Retrieval", duration: "15 min", urgency: "upcoming", done: false },
    ],
  },
  {
    date: "Mon 22 Jun (Week 3)",
    items: [
      { topic: "Full Week 1 — Interleaved with Week 2", type: "Mixed Quiz", duration: "20 min", urgency: "upcoming", done: false },
    ],
  },
  {
    date: "Mon 6 Jul (Month 1)",
    items: [
      { topic: "Week 1 — Spaced Retrieval Checkpoint", type: "Closed-book Quiz", duration: "20 min", urgency: "upcoming", done: false },
    ],
  },
];

const typeTagColors: Record<string, { bg: string; color: string }> = {
  Flashcard: { bg: "rgba(200,135,58,0.12)", color: "#A8692A" },
  Elaboration: { bg: "rgba(69,82,64,0.1)", color: "#455240" },
  Retrieval: { bg: "rgba(122,154,106,0.12)", color: "#4A7040" },
  "Mixed Quiz": { bg: "rgba(139,115,85,0.12)", color: "#6B5532" },
  "Closed-book Quiz": { bg: "rgba(69,82,64,0.1)", color: "#3D4830" },
};

const card: React.CSSProperties = {
  background: "#FFFFFF",
  borderRadius: "16px",
  border: "1px solid rgba(156,132,102,0.14)",
  boxShadow: "0 1px 4px rgba(100,80,60,0.06)",
};

export function ReviewSchedule() {
  return (
    <div className="flex-1 overflow-y-auto p-8" style={{ fontFamily: "'Inter', sans-serif", background: "#F4EFE6" }}>
      <div className="max-w-2xl mx-auto">
        <div className="mb-6">
          <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: "10px", color: "#8A7F72", letterSpacing: "0.12em" }} className="uppercase mb-2">
            Spaced Repetition Schedule
          </div>
          <h1 style={{ fontFamily: "'Playfair Display', serif", fontSize: "26px", fontWeight: 700, color: "#2D2820" }} className="mb-1">
            Review Schedule
          </h1>
          <p style={{ fontSize: "13px", color: "#8A7F72" }}>
            Generated by the spaced repetition algorithm. Optimal gaps based on Cepeda et al. (2006): ~10–20% of retention interval.
          </p>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-3 gap-3 mb-6">
          {[
            { label: "Items due today", value: "3", color: "#B5503A", bg: "rgba(181,80,58,0.08)", sub: "2 overdue" },
            { label: "This week", value: "8", color: "#C8873A", bg: "rgba(200,135,58,0.08)", sub: "~55 min total" },
            { label: "Active cards", value: "18", color: "#455240", bg: "rgba(69,82,64,0.08)", sub: "Week 1 deck" },
          ].map((s) => (
            <div key={s.label} className="rounded-2xl p-4 text-center" style={{ background: s.bg, border: `1px solid ${s.color}20` }}>
              <div style={{ fontFamily: "'Playfair Display', serif", fontSize: "26px", fontWeight: 700, color: s.color }} className="mb-0.5">{s.value}</div>
              <div style={{ fontSize: "12px", color: "#2D2820" }}>{s.label}</div>
              <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: "9px", color: "#8A7F72" }} className="mt-1">{s.sub}</div>
            </div>
          ))}
        </div>

        {/* Research callout */}
        <div style={card} className="p-4 mb-6 flex gap-3">
          <Calendar size={16} color="#8A7F72" className="flex-shrink-0 mt-0.5" />
          <p style={{ fontSize: "12px", lineHeight: 1.65, color: "#7A7068" }}>
            <span style={{ color: "#2D2820", fontWeight: 500 }}>Why this spacing?</span> Cepeda et al. (2006) meta-analysed 317 experiments and found the optimal review gap is ~10–20% of the retention interval.
            For a 1-year retention goal, review monthly. Spacing is most powerful when combined with retrieval — "spaced retrieval practice."
          </p>
        </div>

        {/* Schedule list */}
        <div className="flex flex-col gap-6">
          {scheduleData.map((day, di) => (
            <div key={di}>
              <div className="flex items-center gap-3 mb-2">
                <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: "11px", fontWeight: 500, color: di === 0 ? "#C8873A" : "#8A7F72" }}>
                  {day.date}
                </div>
                <div className="flex-1 h-px" style={{ background: "rgba(156,132,102,0.15)" }} />
                <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: "10px", color: "#8A7F72" }}>
                  {day.items.reduce((acc, item) => acc + parseInt(item.duration), 0)} min
                </div>
              </div>
              <div className="flex flex-col gap-2">
                {day.items.map((item, ii) => (
                  <div key={ii} className="flex items-center gap-3 px-4 py-3 rounded-xl" style={{ background: "#FFFFFF", border: "1px solid rgba(156,132,102,0.12)" }}>
                    <button className="flex-shrink-0" style={{ color: "#C5BDB4" }}>
                      {item.done ? <CheckCircle2 size={16} color="#7A9A6A" /> : <Circle size={16} />}
                    </button>
                    <span style={{ fontSize: "13px", color: "#2D2820" }} className="flex-1">{item.topic}</span>
                    <span style={{
                      fontFamily: "'JetBrains Mono', monospace", fontSize: "10px", fontWeight: 500,
                      ...(typeTagColors[item.type] || { bg: "#EDE7DC", color: "#7A6448" }),
                      background: (typeTagColors[item.type] || { bg: "#EDE7DC" }).bg,
                      color: (typeTagColors[item.type] || { color: "#7A6448" }).color,
                      padding: "2px 8px", borderRadius: "6px",
                    }}>
                      {item.type}
                    </span>
                    <span style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: "10px", color: "#8A7F72" }} className="flex items-center gap-1">
                      <Clock size={10} /> {item.duration}
                    </span>
                    {item.urgency !== "upcoming" && (
                      <span style={{ fontSize: "10px", fontWeight: 600, color: item.urgency === "overdue" ? "#B5503A" : "#C8873A" }}>
                        {item.urgency === "overdue" ? "OVERDUE" : "DUE"}
                      </span>
                    )}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Review arc */}
        <div style={card} className="mt-8 p-6">
          <h3 style={{ fontFamily: "'Playfair Display', serif", fontSize: "16px", fontWeight: 600, color: "#2D2820" }} className="mb-4">
            Your 4-Week Review Arc
          </h3>
          <div className="flex items-center">
            {[
              { label: "Day 1", sub: "Initial study", active: true },
              { label: "Day 2", sub: "1st review", active: true },
              { label: "Day 7", sub: "2nd review", active: false },
              { label: "Day 14", sub: "3rd review", active: false },
              { label: "Day 30", sub: "4th review", active: false },
            ].map((node, i, arr) => (
              <div key={i} className="flex items-center flex-1">
                <div className="flex flex-col items-center gap-1">
                  <div className="w-3 h-3 rounded-full border-2" style={{ borderColor: node.active ? "#C8873A" : "rgba(156,132,102,0.3)", background: node.active ? "#C8873A" : "#FFFFFF" }} />
                  <div style={{ fontFamily: "'JetBrains Mono', monospace", fontSize: "9px", fontWeight: 500, color: node.active ? "#C8873A" : "#8A7F72" }}>{node.label}</div>
                  <div style={{ fontSize: "9px", color: "#8A7F72", textAlign: "center", width: "48px" }}>{node.sub}</div>
                </div>
                {i < arr.length - 1 && <div className="flex-1 h-px mb-5 mx-1" style={{ background: "rgba(156,132,102,0.2)" }} />}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
